### ISSUE TITLE
TypeError: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by flomok** [leeyegy/SimDR#21]
Traceback (most recent call last):
  File "E:/python_console/pose_2/SimCC/tools/train.py", line 258, in <module>
    main()
  File "E:/python_console/pose_2/SimCC/tools/train.py", line 82, in main
    update_config(cfg, args)
  File "E:\python_console\pose_2\SimCC\tools\..\lib\config\default.py", line 147, in update_config
    cfg.merge_from_list(args.opts)
  File "E:\ana\envs\ptorch\lib\site-packages\yacs\config.py", line 224, in merge_from_list
    len(cfg_list) % 2 == 0,
TypeError: object of type 'NoneType' has no len()

**Comment by flomok** [comment]
please,I am a little anxious, which wise man to help me！

**Comment by leeyegy** [comment]
It seems that your cfg_list may be None, you may check the content of cfg_list~

**Comment by flomok** [comment]
Thanks for your reply, but the files under lib/config are all exist, and in train.py the args function  also passes in the "-- cfg" parameter. How can I see if the "cfg list" is empty?

**Comment by flomok** [comment]
I have already solved, may be the problem of the download file, thank you！
